# Generated by Django 4.2.5 on 2023-10-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGalleryAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='Date',
            field=models.DateTimeField(auto_created=True, blank=True),
        ),
    ]
