# Generated by Django 4.2.5 on 2023-10-04 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGalleryAPI', '0002_alter_photo_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='Locataion',
            new_name='Location',
        ),
    ]
