# Generated by Django 4.2.5 on 2023-10-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGalleryAPI', '0003_rename_locataion_photo_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
