# Generated by Django 4.2.5 on 2023-11-16 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGalleryAPI', '0005_person_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CroppedFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Path', models.CharField(max_length=200)),
                ('OriginalPhoto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartGalleryAPI.photo')),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartGalleryAPI.person')),
            ],
        ),
    ]
