# Generated by Django 4.2.5 on 2023-11-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGalleryAPI', '0007_photo_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
