# Generated by Django 4.2.5 on 2023-11-28 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SmartGalleryAPI', '0008_alter_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('Name', 'User')},
        ),
    ]
