# Generated by Django 4.2.5 on 2023-11-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGalleryAPI', '0010_photo_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='Tag',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
