# Generated by Django 4.2.5 on 2023-12-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGalleryAPI', '0012_alter_photo_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='Location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
