# Generated by Django 4.2.5 on 2023-12-20 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGalleryAPI', '0013_alter_photo_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='Location',
        ),
    ]
